Angular patients list
OrangeFlag/AliSOS pull request #18
Opened 2019-11-17 19:56 UTC by karasikrus

#16 
тут тоже самое примерно, но на ангуляре
я не знаю, как это деплоить, но локально `npm start` из папочки с мок-сервером работает.
даже если страничка будет недоступна, то старая всё ещё есть
а потом ещё @MettusEkaterina сделает _КРАСUВО_

2019-11-17 22:50 UTC, OrangeMemes commented on AliSOS Mock clinic client/patients-list/README.md
> +This project was generated with [Angular CLI](https://github.com/angular/angular-cli) version 8.3.19.
cмешно

2019-11-17 22:50 UTC, OrangeMemes commented on AliSOS Mock clinic client/patients-list/e2e/src/app.e2e-spec.ts
> +    expect(page.getTitleText()).toEqual('patients-list app is running!');
лучше никаких тестов, чем такие (если даже эти запустить, то они не пройдут)

я бы удалил. здесь или в отдельном ПР

2019-11-17 22:50 UTC, OrangeMemes commented on AliSOS Mock clinic client/patients-list/e2e/protractor.conf.js
> +// Protractor configuration file, see link for more information
если у тебя нет нормальных рабочих тестов, которые юзают протрактор, то нужен ли он тебе?

2019-11-17 22:50 UTC, OrangeMemes commented on AliSOS Mock clinic client/patients-list/e2e/src/app.po.ts
> +import { browser, by, element } from 'protractor';
вообще всю папку e2e грохнуть бы

2019-11-17 22:50 UTC, OrangeMemes commented on AliSOS Mock clinic client/patients-list/src/app/app-routing.module.ts
> +const routes: Routes = [];
сос мыслом

2019-11-17 22:50 UTC, OrangeMemes commented on AliSOS Mock clinic client/patients-list/src/app/app.component.spec.ts
> +    expect(compiled.querySelector('.content span').textContent).toContain('patients-list app is running!');
тоже дефолтные тесты, которые не работают

2019-11-17 22:50 UTC, OrangeMemes commented on AliSOS Mock clinic client/patients-list/src/app/patients.service.ts
> +  private apiUrl = 'http://localhost:3000/api/patients/'
нужно вынести в конфиг

2019-11-17 22:50 UTC, OrangeMemes commented on AliSOS Mock clinic client/patients-list/src/app/patients/patients.component.html
> +      <div class="doctorType" *ngIf="patient.doctortype; else elseBlock">{{patient.doctortype}}</div>
возможно вы хотели написать
`<div class="doctorType">{{patient.doctortype || "doctor is not assigned"}}</div>`

2019-11-17 22:50 UTC, OrangeMemes commented on AliSOS Mock clinic client/patients-list/src/environments/environment.ts
> +  getPatientsUrl: "http://localhost:3000/api/patients/"
я этот URL уже видел

2019-11-17 22:50 UTC, OrangeMemes commented
у тебя куча всяких огромных штук в директории `AliSOS Mock clinic server/public/patients-list/`, например, полифиллы. это точно должно у нас в репе быть?

2019-11-17 22:53 UTC, OrangeMemes commented on AliSOS Mock clinic client/patients-list/src/app/patients.service.ts
> +  private apiUrl = 'http://localhost:3000/api/patients/'
и подумай, может быть здесь вообще сработает относительный урл, типа `/api/patients/`

2019-11-17 22:54 UTC, vladislavsheludchenkov requested changes
критично -- про то, что у тебя прямо в гите полифиллы лежат, и про то, что у тебя собственный apiUrl не из конфига тянется и не относительный

остальное можно по желанию исправить сейчас или в отдельном пулл-реквесте или вообще не исправлять

2019-11-17 23:07 UTC, karasikrus commented on AliSOS Mock clinic client/patients-list/src/environments/environment.ts
> +  getPatientsUrl: "http://localhost:3000/api/patients/"
не видел

2019-11-20 17:57 UTC, karasikrus commented
Полифилы не поменял, апи поменял
и стили подъехали

2019-11-21 19:54 UTC, karasikrus commented
полифилы поменял, апи урл достаётся из конфига, но не относительный

2019-11-21 20:45 UTC, vladislavsheludchenkov approved these changes
мне очень не понравилось, то можно мержить. в следующем спринте доработаем.

2019-11-21 20:45 UTC, OrangeMemes commented on AliSOS Mock clinic server/patients-list/src/app/mock-patients.ts
> +export const PATIENTS: Patient[] = [{
это ещё что такое

2019-11-21 20:45 UTC, OrangeMemes commented on AliSOS Mock clinic server/patients-list/src/environments/environment.prod.ts
> +  apiUrl: "https://mock-clinique.herokuapp.com/"
очень сомнительная штука для конфигов, которые лежат в репозитории

2019-11-21 20:45 UTC, OrangeMemes commented on AliSOS Mock clinic server/patients-list/src/environments/environment.prod.ts
> +  apiUrl: "https://mock-clinique.herokuapp.com/"
исправлять не нужно

2019-11-21 21:11 UTC, karasikrus commented on AliSOS Mock clinic server/patients-list/src/app/mock-patients.ts
> +export const PATIENTS: Patient[] = [{
забыл удалить

2019-11-24 19:28 UTC, merged