feat: add README.md
OrangeFlag/AliSOS pull request #21
Opened 2019-11-21 09:44 UTC by OrangeFlag

Resolve #14

2019-11-21 20:26 UTC, vladislavsheludchenkov requested changes
третий пункт из задачи совсем не выполнен, по остальным тоже есть вопросы

2019-11-21 20:26 UTC, OrangeMemes commented on README.md
> +Проект находится в Alpha версии и доступен на платформе Алисы только в тестовом режиме
это неправда

2019-11-21 20:26 UTC, OrangeMemes commented on README.md
> +* mock сервис клиники [опционально]
просто сервис клиники, не обязательно он должен быть ненастоящим))

2019-11-21 20:26 UTC, OrangeMemes commented on README.md
> +* запущенный инстанс Postgres, приложения создаст необходимые таблицы самостоятельно при их отсутствии
не только инстанс постгрес, но и саму database там

2019-11-21 20:26 UTC, OrangeMemes commented on README.md
> +# External Clinic API
а почему в ридми описание API в такой странной, почти нечеловекочитаемой нотации? мне казалось, что здесь должно быть для людей.

2019-11-21 20:26 UTC, OrangeMemes commented on README.md
> +              type: integer
здесь не интежер, а побольше число (очень побольше)

2019-11-21 20:26 UTC, OrangeMemes commented on src/main/kotlin/io/sos/alisos/Application.kt
> +            url = System.getenv("DB_URL"),
это нужно тянуть из конфига (а в конфиге уже ссылаться на переменную окружения)

2019-12-15 21:21 UTC, vladislavsheludchenkov reviewed
Посмотрел, мне очень понравилось

2019-12-15 21:21 UTC, OrangeMemes commented on build.gradle.kts
> +import javax.swing.UIManager.put
а вот тут что-то прикола не понял вообще

2019-12-15 21:21 UTC, OrangeMemes commented on src/main/kotlin/io/sos/alisos/domain/MessageInfo.kt
> + * @param yes user clicked yes
```suggestion
 * @param yes user clicked or said yes
```

2019-12-15 21:21 UTC, OrangeMemes commented on src/main/kotlin/io/sos/alisos/domain/MessageInfo.kt
> + * @param no user clicked no
```suggestion
 * @param yes user clicked or said no
```

2019-12-15 21:21 UTC, OrangeMemes commented on src/main/kotlin/io/sos/alisos/domain/RequestDomain.kt
> + * Data received from Alice.
Может, добавить ссылку на протокол? https://yandex.ru/dev/dialogs/alice/doc/protocol-docpage

2019-12-16 07:36 UTC, OrangeFlag commented on build.gradle.kts
> +import javax.swing.UIManager.put
Я тоже(

2019-12-16 17:39 UTC, vladislavsheludchenkov approved these changes
ь

2019-12-16 17:39 UTC, merged